// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynpxsnaglroxnttvnsop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlucHhzbmFnbHJveG50dHZuc29wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjI2NDAsImV4cCI6MjA2NjU5ODY0MH0.MOB6GiZkuGs4n7EWoTa5CUXYPHyy7lr_kRYHBrxdqzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);